export const competitions =[
  {
    "Event Name": "Eastern Solo Singing- “Grounded in roots, Alive with Rhythm”",
    "Description": "This theme embodies the deep connection between tradition and innovation in Eastern music and performance. In this eastern solo performance, this theme celebrates artists who carry forward the essence of their cultural origins while infusing it with new life and personal expression.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50 rs per entry from a Institute",
    "Lead Name": "Aritrita Brahma",
    "Lead Contact Number": 9354397235,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Common Hall",
    "Card Image": "eastern_solo_singing.png",
    "Rules": "Open to all individuals; no group performances allowed. Performance Duration: 3-4 minutes. Max 3 participants per college. Song must be Eastern-style (Classical, Folk, Contemporary). No explicit lyrics. Live accompaniment encouraged. Karaoke tracks must be submitted 48 hours in advance. Judging based on singing only. Only instrumental backing tracks allowed. Unfair practices lead to disqualification. Arrive 30 minutes early. Valid ID required.",
    "Judging Criteria": "Sur (Melody & Pitch Accuracy): 10\nTaal (Rhythm & Timing): 10\nBhava (Expression & Emotion): 10\nPronunciation & Clarity of Lyrics: 10\nStage Presence & Confidence: 10",
    "Certifications": "Certificates and cash prizes for top 3. E-certificates for all participants."
  },
  {
    "Event Name": "Western Solo Singing- “Groove and Rhythm”",
    "Description": "Get ready to take the stage and make the audience groove with your beats! This event is all about rhythm, flow, and musicality.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Jayant Bavouria",
    "Lead Contact Number": 9541410526,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Open Mic Stage",
    "Card Image": "western_solo_singing.png",
    "Rules": "Time Limit: 3-4 minutes. No vulgar or inappropriate content. One instrumentalist allowed but not judged. Max 3 participants per institute. Must stick to Western style (use Western scales, harmonies, vocal techniques). Any language allowed if aligned with Western music. Background tracks must be submitted 48 hours in advance. Judges’ decision is final. Arrive 30 minutes early. Valid ID required.",
    "Judging Criteria": "Musicality: 10\nVocal Skill: 20\nCreativity: 10\nAudience Engagement: 5\nTheme Alignment: 10\nOverall Impact: 5",
    "Certifications": "Cash prizes for top 3. Physical certificates for winners, e-certificates for participants."
  },
  {
    "Event Name": "Duet Singing- “Two Voices, One Nation, Infinite Cultures.”",
    "Description": "Celebrate India’s rich cultural heritage through duet performances—classical, folk, regional, or contemporary!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Shivam",
    "Lead Contact Number": 9149454230,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Open Mic Stage",
    "Card Image": "duet singing.png",
    "Rules": "Register in pairs (any gender mix). Open to all age groups. Valid ID required. Max 3 duets per institute. Must reflect Indian culture (classical, folk, fusion). Duration: 3-5 minutes + 30s grace. No offensive content. Tracks due 48 hours before event. Main singing must be live. Bring own instruments. Report 1 hour early. Judges' decision is final.",
    "Judging Criteria": "Cultural Relevance: 15\nVocal Quality: 10\nCreativity & Coordination: 15\nExpression & Stage Presence: 10",
    "Certifications": "Cash prizes for top 3. Physical certificates for winners, e-certificates for participants."
  },
  {
    "Event Name": "Battle Of Bands- “Roots to Rise, Rhythms to Rock!”",
    "Description": "A fusion showdown where Indian folk meets Bollywood and indie rock on one electrifying stage!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs",
    "Lead Name": "Gurmeet",
    "Lead Contact Number": 8899433889,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Main Stage",
    "Card Image": "battle of bands.png",
    "Rules": "3-10 members per band. Max 2 bands per institute. 20 min total (incl. 5 min setup). No backing tracks. Bring own instruments. Basic drums/amps provided. Judged on fusion, creativity, musicality, stage presence, audience response. No hate/political content. Damages are band’s responsibility. Report 30 minutes early. Valid ID required.",
    "Judging Criteria": "Fusion: 20\nCreativity: 10\nMusicality: 10\nStage Presence: 10\nAudience Response: 10",
    "Certifications": "Cash prizes for top 3. Physical certificates for winners, e-certificates for participants."
  },
  {
    "Event Name": "Solo Instrumental- “Let Your Music Speak!”",
    "Description": "Let your instrument tell your story—no words needed. Just passion, rhythm, and soul.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Rajiv Singh",
    "Lead Contact Number": 7408784223,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Open Mic Stage",
    "Card Image": "solo instrumental.png",
    "Rules": "Max 5 minutes performance + 1 minute setup. Max 3 participants per institute. Any instrument allowed. Solo only—no accompaniment. Avoid inappropriate acts. Bring your own instrument. Judges’ decision is final. Valid ID required.",
    "Judging Criteria": "Technique & Accuracy: 10\nMusicality & Expression: 10\nStage Presence & Engagement: 5\nOverall Presentation: 5",
    "Certifications": "Cash prizes for top 3. Physical certificates for winners, e-certificates for participants."
  },
  {
    "Event Name": "Rap Battle- Bars Over Bluffs, Rhymes Over Ruffs!",
    "Description": "Step up and drop fire bars! One mic, one beat, one chance to rule the stage.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Aditya Shresth",
    "Lead Contact Number": 8082525295,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Open Mic Stage",
    "Card Image": "rap battle.png",
    "Rules": "One participant at a time. 3 minutes per rapper. Max 3 per college. Original content only. Optional beat or acapella. No foul/offensive language. Tracks due 48 hours early. Judged on lyricism, flow, delivery, stage presence, audience engagement. Report 30 minutes early. Valid ID required.",
    "Judging Criteria": "Lyricism: 10\nFlow: 10\nDelivery: 10\nStage Presence: 10\nAudience Engagement: 10",
    "Certifications": "Cash prizes for top 3. Physical certificates for winners, e-certificates for participants."
  },
  {
    "Event Name": "Beat Box- “Ancient Roots, Modern Grooves”",
    "Description": "A beatbox experience blending tribal rhythm with urban edge—pure vocal fire!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Aditya Shresth",
    "Lead Contact Number": 8082525295,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Open Mic Stage",
    "Card Image": "beatbox.png",
    "Rules": "Solo only. Max 3 per college. No pre-recorded sounds. Tribal/nature-inspired beats encouraged. 90 seconds per performance. Judged on technical skill, creativity, musicality, stage presence, originality. Report 30 minutes early. Valid ID required.",
    "Judging Criteria": "Technical Skill: 10\nCreativity: 10\nMusicality: 10\nStage Presence: 10\nOriginality: 10",
    "Certifications": "Cash prizes for top 3. E-certificates for all participants."
  }
];

export const DancingEvents = [
  {
    "Event Name": "Eastern Solo Dancing- “The Art of Dance, The Essence of Culture!”",
     "Description": "The Solo Eastern Dance Competition is a celebration of tradition, grace, and cultural storytelling. Dancers will captivate the stage with classical, folk, and contemporary Eastern dance forms, showcasing elegance, technique, and deep-rooted heritage. Each performance is a journey through rhythm and expression, honoring the rich traditions of the East. Join us as we witness the beauty of solo artistry, where every step tells a timeless story!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Abhiraj Kanteshwar Roy",
    "Lead Contact Number": 7298212637,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Common Hall",
    "Card Image": "solo dance eastern.png",
    "Rules": "Each performance should be between 3 to 4 minutes. Per college a maximum of 3 participants are allowed. Songs should be in line with Eastern cultural themes and must not contain offensive or inappropriate content. Contestants will be judged on expression, technical skill, accuracy of dance moves, and creativity in choreography. Participants must perform an Eastern-style dance like Bharatanatyam, Kathakali, Kathak, Manipuri, etc. Costumes, gestures, and performances must be respectful and free from any obscenities or controversial content. Any violation may result in disqualification. Dangerous stunts, high-risk moves, or any form of vulgarity are strictly prohibited. Props are allowed but must be safe, easy to handle, and should not damage the stage. Dancers will be evaluated based on skills, stage presence, synchronization/accuracy with music, and overall impact. Participants are requested to report 30 minutes prior to the competition. The judge's decision would be final. Music tracks must be submitted in MP3 format at least 2 days before the event. Participants must adhere to schedule and stage limits provided by organizers. All participants are required to possess a valid identification document.",
    "Judging Criteria": "Total marks: 50\nCreativity – fresh interpretation, artistic use of space.\nMoves/Technique – Clarity, precision, variety, and control in movement.\nExpression – Strong facial expressions, gestures, emotional storytelling.\nStage Presence – Confidence, grace, audience engagement, command of stage.\nCultural Authenticity – Faithful to traditional style, costume, music, and context.\nOverall Impact – Cohesive, memorable, and well-balanced performance.\n\nCreativity (10 marks)\nMoves (10 marks)\nExpression (10 marks)\nStage Presence (10 marks)\nCultural Authenticity (10 marks)",
    "Certifications": "Certificates & cash prizes for the Top 3 Winners. E-Certificates for all participants—because every effort deserves recognition."
  },
  {
    "Event Name": "Western Solo Dancing- 'Where dusty trails meet dynamic beats'",
    "Description": "A solo western dance is a captivating performance that embodies the spirit of the American West, often blending elements of country, folk, and even modern dance styles. It's a showcase of individual expression, strength, and storytelling, told through movement.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Janvi Duge",
    "Lead Contact Number": 9699408586,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Common Hall",
    "Card Image": "solo dance western.png",
    "Rules": "The time limit for each performance should be 3-4 minutes. Western attire is typically expected, such as cowboy boots, hats, and clothing that evokes the Old West. Costumes should be appropriate and not overly revealing. When selecting clothing, please ensure it is appropriate and avoids any offensive or inappropriate content. Contestants must be dressed up in a sense that does not reflect any type of obscenity or any other subject matter not suitable for a family audience. Any such act will lead to disqualification of the participant or the team. Performance should not include any stunts and/or moves with high-risk and vulgarity. If there is use of props, they must generally be safe and not cause damage to the stage. Number of participants allowed per school/college is 3. All karaoke and background tracks must be provided at least 48 hours before the scheduled event. All participants are required to possess a valid identification document.",
    "Judging Criteria": "Total marks:50\nCreativity – Unique choreography and fresh interpretation.\nMoves & Technique – Clean execution, variety, and control.\nExpression – Emotions, facial expressions, and connection to music.\nStage Presence – Confidence, charisma, and command of space.\nCrowd Engagement – Interaction and entertainment value.\n\nCreativity (10 marks)\nMoves (10 marks)\nExpression (10 marks)\nStage Presence (10 marks)\nCrowd engagement (10 marks)",
    "Certifications": "Certificates & cash prizes for the Top 3 Winners. E-Certificates for all participants—because every effort deserves recognition."
  },
  {
    "Event Name": "Duet Freestyle- 'Echoes of Time - A Timeless Beat, A Modern Pulse.'",
    "Description": "'Echoes of Time' is a celebration of dance through the ages, where tradition meets innovation. It blends classical rhythms with contemporary expressions, showcasing the evolution of movement across generations. Each performance is a bridge between past and present, honoring heritage while embracing modern creativity. From folk to freestyle, ballet to hip-hop—this is where history and future dance as one.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "80rs",
    "Lead Name": "Kiran",
    "Lead Contact Number": 6006624997,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Main Stage",
    "Card Image": "DuetFreeStyle.png",
    "Rules": "Team Composition: Colleges and schools interested in participating may introduce a maximum of 3 Pairs. (The pair can include both boys, both girls or a boy and a girl). Theme: The performance must incorporate elements of both traditional and modern dance forms, ensuring a harmonious fusion of past and present. Performance Duration: 3 to 5 minutes (strictly enforced). Music Submission: All performance tracks must be submitted to the organizing committee at least 48 hours before the event. Costumes & Props: Attire must reflect the thematic fusion and maintain cultural sensitivity. Props are permitted if they enhance the performance without causing delays or hazards. Performance Rules: Artistic Freedom with Structure: While creativity is encouraged, performances must uphold the integrity of both traditional and modern dance styles. Discipline and Decorum: Respect for cultural traditions is paramount—any performance deemed offensive, inappropriate, or disrespectful to any heritage or community will result in immediate disqualification. Time Discipline: Exceeding the time limit will lead to penalties. Stage Etiquette: Performers must ensure smooth stage entry and exit without disrupting the event flow. The judge's decision would be final. All participants are required to possess a valid identification document.",
    "Judging Criteria": "Total marks: 100\nCreativity & Innovation (20%) – The seamless fusion of dance styles and originality of concept.\nSynchronization & Coordination (20%) – The harmony between partners, timing, and execution.\nTheme Adherence (20%) – Authenticity in blending heritage with modernity.\nStage Presence & Expression (20%) – Confidence, engagement, and storytelling through movement.\nOverall Impact (20%) – The lasting impression left on the audience and judges.\n\nCreativity & Innovation (20 marks)\nTheme Adherence (20 marks)\nSynchronization & Coordination (20 marks)\nStage Presence & Expression (20 marks)\nOverall Impact (20 marks)",
    "Certifications": "Cash prizes & certificates will be given to the final top 3 winners. E-Certificates would be provided to all the participants."
  },
  {
    "Event Name": "Dance Battle- 'Dance Your Path, Own the Beat'",
    "Description": "Step onto the stage where movement meets the journey! It is not just a dance battle—it’s a fusion of paths and pulses, a collision of styles and stories. Dancers will channel the energy of different routes—cultural, personal, or urban—while riding the rhythm that drives them forward.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs/team",
    "Lead Name": "Janvi Duge",
    "Lead Contact Number": 9699408586,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Common Hall",
    "Card Image": "dancebattle.png",
    "Rules": "Team Composition: Each team must consist of exactly 5 members and each institute is allowed 1 team only. No substitutions allowed once the competition starts. Attire: No offensive or inappropriate clothing. Coordinated costumes are optional but can add to the visual impact. Music & Style: Music will be selected by the organizers or a DJ on-spot. Styles may include hip-hop, street, freestyle, popping, locking, krump, etc.",
    "Judging Criteria": "There are total 3 rounds, each round has its own rules, which will be notified on the event day.",
    "Certifications": "Certificates & cash prizes for the Top 3 Winners. E-Certificates for all participants—because every effort deserves recognition."
  },
  {
    "Event Name": "Choreonight- 'Feel the Rhythm, Live the Moment'",
    "Description": "Get ready to witness an electrifying dance battle where past meets present! Modern Hits & Retro Rivals is a dynamic group dance competition celebrating the evolution of music and movement. Teams will light up the stage with high-energy performances that blend the groovy charm of retro beats with the bold vibes of modern hits. It’s more than just a competition — it’s a celebration of style, creativity, and rhythm across generations. Whether you're throwing it back to disco and pop classics or bringing the fire with current chart-toppers, each performance should tell a story of contrast, fusion, or transition between eras. Which team will rule the rhythm — the retro rebels or the modern mavens? Let the showdown begin!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs/group",
    "Lead Name": "Akansha Shukla",
    "Lead Contact Number": 9555615498,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "",
    "Venue": "Main Stage",
    "Card Image": "choreo night.png",
    "Rules": "The team must consist of a minimum of 10 and a maximum of 25 members. A maximum of 1 entry is allowed as a team per institute. Performances must include both retro and modern elements — in music, choreography, or costume. Fusion of dance styles is encouraged (e.g., hip-hop, disco, jazz funk, contemporary, etc.). The performance duration should be between 5 to 10 minutes. Exceeding the time limit will lead to point deductions. Music tracks must be submitted in MP3 format at least 2 days before the event. Use of props is allowed, but teams must manage setup and removal within 2 minutes. Props involving fire, liquids, or hazardous materials are strictly prohibited. Any vulgar or inappropriate content (in music, movements, or costume) will lead to disqualification. Teams must adhere to schedule and stage limits provided by organizers. Judges' decisions are final and binding. All participants are required to possess a valid identification document. All karaoke and background tracks must be provided at least 48 hours before the scheduled event.",
    "Judging Criteria": "Total marks: 100\n1. Choreography & Creativity – use of space, and innovative ideas.\n2. Dance Moves – Technique, variety, and clean execution.\n3. Synchronization & Coordination – Group timing and seamless transitions.\n4. Theme & Storytelling – Clear theme, emotional depth, and narrative flow.\n5. Stage Presence & Expression – Confidence, expressions, and audience engagement.\n6. Costume & Visual Appeal – Thematic relevance, color coordination, and overall look\nChoreography & Creativity (30 marks)\nSynchronization & Coordination (25 marks)\nTheme Relevance & Storytelling (20 marks)\nStage Presence & Expression (15 marks)\nCostume & Visual Appeal (10 marks)",
    "Certifications": "Certificates & cash prizes for the Top 3 Winners. E-Certificates for all participants—because every effort deserves recognition."
  }
];



export const Workshop = [
  {
    "Event Name": "Henna Art",
    "Description": "Discover the ancient art of Henna design and application. Learn various patterns and techniques from experienced artists. Get hands-on experience and create intricate designs. Take home your creations and learn about Heena aftercare. Explore cultural significance and traditional art forms.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Alok Ranjan",
    "Lead Contact Number": "7209666594",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "2",
    "Venue": "LH",
    "Card Image" : "henna.png"
  },
  {
    "Event Name": "Salsa Dance Workshop",
    "Description": "Learn energetic and passionate Salsa dance styles. Discover Cuban, Puerto Rican, and Colombian rhythms. Learn basics, including steps and movements. Practice leading and following techniques. Improve coordination and dance skills. Learn from experienced instructors and get feedback.",
    "NIT Entry Fee": "SOLO ENTRY : 300rs  , DUO ENTRY : 500rs",
    "Outside Entry Fee": "SOLO ENTRY : 300rs  , DUO ENTRY : 500rs",
    "Lead Name": "Alok Ranjan",
    "Lead Contact Number": "7209666594",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "1",
    "Venue": "Amphitheatre (near activity centre)",
    "Card Image" : "salsa.png"
  },
  {
    "Event Name": "Sculpture Making",
    "Description": "Unleash your creativity and learn sculpture-making techniques. Explore materials like clay, wire, and wood. Get hands-on experience with tools and equipment. Discover principles of balance and composition. Create your own sculpture and take it home. Learn from experienced sculptors.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Alok Ranjan",
    "Lead Contact Number": "7209666594",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "2",
    "Venue": "Amphitheatre (near activity centre)",
    "Card Image" : "sculpture112.png"
  },
  {
    "Event Name": "Crochet",
    "Description": "Learn relaxing and creative crochet techniques. Discover stitches, hooks, and yarns. Get hands-on experience with projects like scarves and hats. Improve hand-eye coordination and fine motor skills. Learn to read patterns and instructions. Take home finished projects.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Alok Ranjan",
    "Lead Contact Number": "7209666594",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "1",
    "Venue": "LH",
    "Card Image" : "crochet(1).png"
  },
  {
    "Event Name": "Fabric Painting",
    "Description": "Learn fabric painting methods, including hand-painting and stamping. Get hands-on experience with paints and brushes. Create unique designs and patterns. Improve color theory and composition skills. Learn to fix and set fabric paint. Take home finished projects.",
    "NIT Entry Fee": "NULL",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Alok Ranjan",
    "Lead Contact Number": "7209666594",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "fabric (1)-1.png"
  },
  {
    "Event Name": "Tattoo Fashion (temporary)",
    "Description": "Learn temporary tattooing techniques, including henna and jagua. Get hands-on experience with application tools. Create unique designs and learn about7 skin safety. Take home creations and learn maintenance tips. Explore cultural significance and body art expression.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs",
    "Lead Name": "Alok Ranjan ",
    "Lead Contact Number": "7209666594",
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day": "2",
    "Venue": "LH",
    "Card Image" : "tattoo(1).png"
  },

  {
    "Event Name": "Mr & Miss Rang-e-Chinar",
    "Description": "Step into the spotlight and embrace your true essence, 'Mr. and Ms. Rang-e-Chinar' is more than just a pageant—it's a celebration of individuality, confidence, and cultural elegance. This competition is designed to bring out the charisma, creativity, and personal expression of every participant.From showcasing impeccable style in couture to exuding unmatched grace and charm, contestants will embark on a journey of self-discovery and artistic presentation. Whether through fashion, performance, or personality, each round will challenge participants to embrace their roots while defining their unique rhythm.This is your chance to shine, to unveil your true self, and to redefine glamour with a touch of authenticity. The stage is yours—own it with Couture and Charisma: The Ultimate Blend! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Deepti Badyal ",
    "Lead Contact Number": 7006863809,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Main Stage",
    "Card Image" : "Mr. & Miss Rangechinar.png"
  },
  {
    "Event Name": "Face Painting",
    "Description": "'Parallel Realities: The World Through Different Eyes' Imagine how the world looks through the eyes of animals, AI, aliens, or even different emotions. ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Shivangi Basu ",
    "Lead Contact Number": 9638298285,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "Face Painting_ Stone Painting.png"
  },
  {
    "Event Name": "Wall Painting",
    "Description": "Singing performance from NIT Srinagar Student band",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Shivangi Basu ",
    "Lead Contact Number": 9638298285,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Campus",
    "Card Image" : "Wall Painting.png"
  },
  {
    "Event Name": "Stone Painting",
    "Description": "'Cultural Tapestry: Heritage and Traditions of Kashmir' Encourages artists to showcase Kashmir’s rich culture, traditions, folklore, and symbols on stones.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Shivangi Basu ",
    "Lead Contact Number": 9638298285,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "Face Painting_ Stone Painting.png"
  },
  {
    "Event Name": "Live Photography",
    "Description": "Step into the world of photography and freeze time with your lens! The Live Photography Event is an exciting competition where participants will showcase their ability to capture stunning moments in real-time. This event is all about creativity, perspective, and storytelling through photographs. Let your camera narrate the world as you see it! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Akshay Kumar ",
    "Lead Contact Number": 6005523966,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Campus",
    "Card Image" : "Live Photography.png"
  },
  {
    "Event Name": "30 Sec Reel Making",
    "Description": "Unleash your creativity in just 30 seconds! Show off your storytelling, editing, and filming skills by creating a short yet impactful reel that captivates the audience. Whether it’s comedy, drama, action, or pure aesthetics—your vision, your story, your moment to shine! Are you ready to reel it, feel it and win it? ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Gyan",
    "Lead Contact Number": 8051005656,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "No Venue",
    "Card Image" : "reel.png",
    "FormLink" : "https://forms.gle/FFcJMTwC6DqhZ4rv7"
  },
  {
    "Event Name": "Meme Making",
    "Description": "Unleash your creativity and humor at our meme-making event . Join us for an evening of laughter and fun as we create hilarious memes that will make your friends LOL! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "NO Fee",
    "Lead Name": "Yash Pratap Singh ",
    "Lead Contact Number": 9103582285,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "Meme Making.png",
    "FormLink" : "https://docs.google.com/forms/d/e/1FAIpQLScZhvCShBFuqza7Eg0A4P98_hEXn0lJgH9dH_500KiHXsmC2A/viewform?usp=dialog"
  },
  {
    "Event Name": "Short Movie Making",
    "Description": "Step into the world of storytelling where culture meets creativity! 'Lights, Culture, Action!' is a short film competition that invites filmmakers to explore the rhythms of tradition and the roots of identity. From folklore and heritage to music and dance, this event celebrates the vibrant fusion of the past and present through the lens of cinema. Participants will craft compelling short films that showcase cultural narratives, artistic expressions, and the evolution of traditions in today’s world. Whether through powerful storytelling, mesmerizing visuals, or rhythmic beats, each film will bring culture to life on screen. Join us for an unforgettable cinematic journey—where every frame echoes heritage, and every rhythm tells a story! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs",
    "Lead Name": "Zeeshan Nazir ",
    "Lead Contact Number": 914957803,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "LH",
    "Card Image" : "Short Movie Making.png",
    "FormLink" : "https://docs.google.com/forms/d/e/1FAIpQLSeXCbKCsuOyvbFLlt_EkrlYiBF7t7LVLYm26E_8OOONEwb6Ew/viewform?usp=dialog"
  },
  {
    "Event Name": "Open Talent Show For Faculties",
    "Description": "Join us for an exciting evening where faculty members step beyond the lecture halls and into the spotlight! This open talent show is a celebration of the hidden artistic, musical, and performance skills of our educators. From singing and dancing to poetry, comedy, and beyond, watch as professors, lecturers, and staff showcase their incredible talents in a fun, engaging, and unforgettable event. ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Anjali Kacher ",
    "Lead Contact Number": 8400357741,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "Open Talent Show for Faculties.png"
  },
  {
    "Event Name": "Tea Time Cronicals",
    "Description": "Teatime Chronicles is a simple and fun storytelling event where students share their stories, and we serve them tea. It is a place to talk, listen, and connect over a warm cup of tea",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Disha ",
    "Lead Contact Number": 6005177134,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Amphitheatre (near activity centre)",
    "Card Image" : "Tea cronicals.png"
  },
    {
      "Event Name": "Stand-Up Comedy",
      "Description": "Serious About Comedy, Giggles loaded Ahead: Stand-Up Comedy Brace yourselves for an unforgettable evening packed with belly laughs, quick wit, and relatable humor! Featuring a lineup of comedic geniuses, this show promises to tickle your funny bone and brighten your day. From hilarious observations about life to side-splitting anecdotes, you'll be taken on a comedic rollercoaster like no other. Whether you're a connoisseur of clever punchlines or a fan of absurd humor, this show guarantees non-stop laughter and entertainment. Grab your friends, and let's turn ordinary moments into extraordinary memories. Are you ready for the fun? Let's get the giggles rolling! ",
      "NIT Entry Fee": "NO Fee",
      "Outside Entry Fee": "50rs",
      "Lead Name": "ABHI BADHERA ",
      "Lead Contact Number": 7732803858,
      "Start Time": "To Be Decided",
      "End Time": "To Be Decided",
      "Day":"",
      "Venue": "Common Hall",
      "Card Image" : "StandupComedy.png"
    },
    {
      "Event Name": "Mimicry",
      "Description": "SGet ready for a fun-filled evening at our college's Mimicry! Watch your favorite celebrities, characters, and professors come to life as talented performers bring them to the stage with hilarious and spot-on impersonations. An event full of laughter, creativity, and unexpected surprises—don’t miss out on the show!",
      "NIT Entry Fee": "NO Fee",
      "Outside Entry Fee": "50rs",
      "Lead Name": "ROHIT PRAJAPAT ",
      "Lead Contact Number": 9596271532,
      "Start Time": "To Be Decided",
      "End Time": "To Be Decided",
      "Day":"",
      "Venue": "Open Mic Stage",
      "Card Image" : "Mimicry.png"
    },
    {
      "Event Name": "Mushaira",
      "Description": "Mushaira is a gathering of poets where words take center stage and emotions flow effortlessly. It is a celebration of expression, rhythm, and storytelling through poetry. With no fixed theme, poets from all genres are welcome to captivate the audience with their verses. Step forward, let your voice be heard, and create an unforgettable experience through the power of words!",
      "NIT Entry Fee": "NO Fee",
      "Outside Entry Fee": "50rs",
      "Lead Name": "Akanksha Shukla ",
      "Lead Contact Number": 9555615498,
      "Start Time": "To Be Decided",
      "End Time": "To Be Decided",
      "Day":"",
      "Venue": "HiTech",
      "Card Image" : "Mushaira.png"
    },
    {
      "Event Name": "Monoacting",
      "Description": "Whether it's a heartfelt monologue, an intense dramatic act, or a light-hearted yet meaningful performance, every expression, every gesture, and every word will bring a story to life. Participants will be judged on their ability to captivate the audience, their expressions, dialogue delivery, and stage presence.So, take the stage, let your voice echo through the fest, and leave the audience mesmerized with your performance. Because sometimes, a single voice is all it takes to move a thousand hearts!",
      "NIT Entry Fee": "NO Fee",
      "Outside Entry Fee": "50rs",
      "Lead Name": "Rishabh Shukla ",
      "Lead Contact Number": 8527109671,
      "Start Time": "To Be Decided",
      "End Time": "To Be Decided",
      "Day":"",
      "Venue": "Common Hall",
      "Card Image" : "Monoacting.png"
    },
    {
      "Event Name": "Poetry",
      "Description": "Step into a world where words paint landscapes, and emotions echo through time! Wel come to an evening of lyrical beauty and heartfelt expressions at NIT Srinagar’s Poetry Event. Under the enchanting theme of Nature & Nostalgia, poets and enthusiasts will gather to celebrate the magic of poetry—where memories intertwine with the whispers of the wind and verses bloom like wildflowers. Whether you seek solace in nature’s embrace or cherish the bittersweet echoes of the past, this event promises a soulful journey through spoken artistry. Come, immerse yourself in rhythm, rhyme, and raw emotion! ",
      "NIT Entry Fee": "NO Fee",
      "Outside Entry Fee": "50rs",
      "Lead Name": "Aakash Kumar",
      "Lead Contact Number": 8493866076,
      "Start Time": "To Be Decided",
      "End Time": "To Be Decided",
      "Day":"",
      "Venue": "Open Mic Stage",
      "Card Image" : "Poetry.png"
    },
    {
      "Event Name": "Drama",
      "Description": "Dramatics is the art of storytelling through performance, blending emotion, expression, and stagecraft to bring characters and narratives to life. It encompasses theater, improvisation, and scripted plays, offering a powerful medium for creativity, entertainment, and social commentary. ",
     "NIT Entry Fee": "NO Fee",
      "Outside Entry Fee": "100rs",
      "Lead Name": "Kumar Sangyanam  ",
      "Lead Contact Number": 9797435297,
      "Start Time": "To Be Decided",
      "End Time": "To Be Decided",
      "Day":"",
      "Venue": "Common Hall",
      "Card Image" : "Drama.png"
    },
    {
      "Event Name": "Ladishah",
      "Description": "Participants will showcase their talent by performing Ladishah, a traditional Kashmiri satirical storytelling art form. The act should be engaging, humorous, and reflect social or cultural themes in an entertaining manner. Rhythm, wit, and creative expression are encouraged to captivate the audience.",
      "NIT Entry Fee": "NO Fee",
      "Outside Entry Fee": "50rs",
      "Lead Name": "Reeba",
      "Lead Contact Number": 6006993971,
      "Start Time": "To Be Decided",
      "End Time": "To Be Decided",
      "Day":"",
      "Venue": "HiTech",
      "Card Image" : "Ladishah.png"
    }
  
];

export const Performances  = [
  {
    "Event Name": "Stand-Up Comedy",
    "Description": "Serious About Comedy, Giggles loaded Ahead: Stand-Up Comedy Brace yourselves for an unforgettable evening packed with belly laughs, quick wit, and relatable humor! Featuring a lineup of comedic geniuses, this show promises to tickle your funny bone and brighten your day. From hilarious observations about life to side-splitting anecdotes, you'll be taken on a comedic rollercoaster like no other. Whether you're a connoisseur of clever punchlines or a fan of absurd humor, this show guarantees non-stop laughter and entertainment. Grab your friends, and let's turn ordinary moments into extraordinary memories. Are you ready for the fun? Let's get the giggles rolling! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "ABHI BADHERA ",
    "Lead Contact Number": 7732803858,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "StandupComedy.png"
  },
  {
    "Event Name": "Mimicry",
    "Description": "SGet ready for a fun-filled evening at our college's Mimicry! Watch your favorite celebrities, characters, and professors come to life as talented performers bring them to the stage with hilarious and spot-on impersonations. An event full of laughter, creativity, and unexpected surprises—don’t miss out on the show!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "ROHIT PRAJAPAT ",
    "Lead Contact Number": 9596271532,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Mushaira",
    "Description": "Mushaira is a gathering of poets where words take center stage and emotions flow effortlessly. It is a celebration of expression, rhythm, and storytelling through poetry. With no fixed theme, poets from all genres are welcome to captivate the audience with their verses. Step forward, let your voice be heard, and create an unforgettable experience through the power of words!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Akanksha Shukla ",
    "Lead Contact Number": 9555615498,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "HiTech",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Monoacting",
    "Description": "Whether it's a heartfelt monologue, an intense dramatic act, or a light-hearted yet meaningful performance, every expression, every gesture, and every word will bring a story to life. Participants will be judged on their ability to captivate the audience, their expressions, dialogue delivery, and stage presence.So, take the stage, let your voice echo through the fest, and leave the audience mesmerized with your performance. Because sometimes, a single voice is all it takes to move a thousand hearts!",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Rishabh Shukla ",
    "Lead Contact Number": 8527109671,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "Monoacting.png"
  },
  {
    "Event Name": "Poetry",
    "Description": "Step into a world where words paint landscapes, and emotions echo through time! Wel come to an evening of lyrical beauty and heartfelt expressions at NIT Srinagar’s Poetry Event. Under the enchanting theme of Nature & Nostalgia, poets and enthusiasts will gather to celebrate the magic of poetry—where memories intertwine with the whispers of the wind and verses bloom like wildflowers. Whether you seek solace in nature’s embrace or cherish the bittersweet echoes of the past, this event promises a soulful journey through spoken artistry. Come, immerse yourself in rhythm, rhyme, and raw emotion! ",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Aakash Kumar",
    "Lead Contact Number": 8493866076,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Open Mic Stage",
    "Card Image" : "vihang.png"
  },
  {
    "Event Name": "Drama",
    "Description": "Dramatics is the art of storytelling through performance, blending emotion, expression, and stagecraft to bring characters and narratives to life. It encompasses theater, improvisation, and scripted plays, offering a powerful medium for creativity, entertainment, and social commentary. ",
   "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "100rs",
    "Lead Name": "Kumar Sangyanam  ",
    "Lead Contact Number": 9797435297,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "Common Hall",
    "Card Image" : "Drama.png"
  },
  {
    "Event Name": "Ladishah",
    "Description": "Participants will showcase their talent by performing Ladishah, a traditional Kashmiri satirical storytelling art form. The act should be engaging, humorous, and reflect social or cultural themes in an entertaining manner. Rhythm, wit, and creative expression are encouraged to captivate the audience.",
    "NIT Entry Fee": "NO Fee",
    "Outside Entry Fee": "50rs",
    "Lead Name": "Reeba",
    "Lead Contact Number": 6006993971,
    "Start Time": "To Be Decided",
    "End Time": "To Be Decided",
    "Day":"",
    "Venue": "HiTech",
    "Card Image" : "Ladishah.png"
  }

];
